version: "3.9"

services:

  subastas_db:
    image: postgres:15
    restart: always
    container_name: certus-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: subastas_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - subastas_network

  subastas_back:
    build: .
    container_name: certus-backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - subastas_db
    environment:
      DATABASE_URL: postgresql://user:password@subastas_db:5432/subastas_db
    volumes:
      - ./backend/templates:/app/templates
      - ./backend/static:/app/static
    networks:
      - subastas_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: certus-pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@certus.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - subastas_network
    depends_on:
      - subastas_db

volumes:
  db_data:
  pgadmin_data:

networks:
  subastas_network:
    driver: bridge