version: "3.9"

services:

  subastas_db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: subastas_db
    volumes:
      - db_data:/var/lib/postgresql/data

  subastas_back:
    build: .
    container_name: certus-backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - subastas_db
    environment:
      DATABASE_URL: postgresql://user:password@subastas_db:5432/subastas_db
    volumes:
      - ./backend/templates:/app/templates   # Para ver cambios SIN rebuild
      - ./backend/static:/app/static         # CSS en tiempo real

volumes:
  db_data:
