version: "3.9"

services:

  subastas_db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: subastas_db
    volumes:
      - db_data:/var/lib/postgresql/data

  subastas_back:
    build: .
    container_name: certus-backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - subastas_db
    environment:
      DATABASE_URL: postgresql://user:password@subastas_db:5432/subastas_db

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - subastas_db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  db_data:
  pgadmin_data:
